package components

// Hooks are the `data-` attribute names this package's markup renders: the
// component hook, the parts inside a component, and the state a controller
// reads. They are the vocabulary a stylesheet addresses a component by, so the
// kernel owns every name in this list — ui.Compose refuses a client rule that
// names one, because such a rule is coupled to markup the kernel may rename.
//
// The list is the kernel's rendered markup, not a style guide: hooks_test.go
// reads this package's sources and refuses a name the markup emits that the list
// omits, and a name the list carries that no markup emits. A component that adds
// a part adds its attribute to both files in the same change.
var Hooks = []string{
	"data-action",
	"data-active",
	"data-alert-actions",
	"data-alert-close",
	"data-alert-dismissible-value",
	"data-alert-icon",
	"data-alert-tone",
	"data-align",
	"data-autoresize-max-rows-value",
	"data-autoresize-min-rows-value",
	"data-badge-count",
	"data-badge-dot",
	"data-badge-remove",
	"data-breadcrumb-ellipsis",
	"data-button-as-link",
	"data-checkbox-active-classes",
	"data-checkbox-bar",
	"data-checkbox-box",
	"data-checkbox-checkmark",
	"data-checkbox-inactive-classes",
	"data-checkbox-indeterminate-value",
	"data-checkbox-input",
	"data-color",
	"data-component",
	"data-confirm-accept",
	"data-confirm-cancel",
	"data-confirm-message",
	"data-controller",
	"data-detail-item",
	"data-disabled",
	"data-element",
	"data-has-badge",
	"data-htmx-modal-clear-on-close-value",
	"data-htmx-modal-close-on-escape-value",
	"data-htmx-modal-open-value",
	"data-lines",
	"data-loading",
	"data-modal-backdrop",
	"data-modal-body",
	"data-modal-cancel",
	"data-modal-close",
	"data-modal-footer",
	"data-modal-panel",
	"data-modal-separator",
	"data-nav",
	"data-page",
	"data-pagination-next",
	"data-pagination-prev",
	"data-pk-icon",
	"data-pk-icon-canonical",
	"data-pk-icon-fallback",
	"data-pk-options",
	"data-pk-row",
	"data-pk-select",
	"data-pk-sort",
	"data-pk-sort-icon",
	"data-pk-value",
	"data-pk-values",
	"data-semantic-role",
	"data-sidebar-brand",
	"data-sidebar-collapsed",
	"data-sidebar-collapsible",
	"data-sidebar-depth",
	"data-sidebar-flavor",
	"data-sidebar-footer",
	"data-sidebar-item",
	"data-sidebar-item-chevron",
	"data-sidebar-item-icon",
	"data-sidebar-item-label",
	"data-sidebar-item-prefix",
	"data-sidebar-search-item",
	"data-sidebar-search-section",
	"data-sidebar-search-text",
	"data-sidebar-section",
	"data-sidebar-section-glyph",
	"data-sidebar-section-header",
	"data-sidebar-section-label",
	"data-sidebar-submenu",
	"data-sidebar-tone",
	"data-size",
	"data-state",
	"data-tabs-active-classes",
	"data-tabs-active-tab-value",
	"data-tabs-contract",
	"data-tabs-inactive-classes",
	"data-tabs-lazy",
	"data-tabs-panel",
	"data-tabs-tab",
	"data-textarea-counter-target",
	"data-textarea-input",
	"data-tone",
	"data-variant",
	"data-weight",
}
