-- The trace the recorded event happened in.
--
-- The trail answers "who did this, when, in which tenant". Since the outbox
-- carries the publisher's W3C trace context (migrations/000028), a row of the
-- trail can also answer "and which request was that" — the join an operator asks
-- for the moment a compliance question becomes an incident question, and the
-- reason this column is worth a migration.
--
-- It is the trace id and not the traceparent string: the same number, in a type a
-- query and an index can answer from, and one that survives a vendor's header
-- format. Nullable, because an event published by a periodic job, or by any
-- process with no collector configured, has no trace to name, and NULL is the
-- honest answer where the zero UUID would be a lie.
--
-- This file is 35 and not the 30 it was written as: main's 000030_tenant_oidc took
-- that number while this one held it, and two owners at one version is the shape the
-- upgrade fixture flattens into one ledger row
-- (apps/platformkit/app_test.go, legacyLayout). An unreleased file moves past the
-- highest number anywhere in the composition rather than a released one, and moving
-- it is free: nothing applied it under another owner, so this source's Adopts stays
-- {10, 15, 23} and this file is a new row for the audit owner rather than a re-owned
-- one.
ALTER TABLE audit_events ADD COLUMN trace_id uuid;
